version: 2
updates:
  - package-ecosystem: "gradle" # Specify Gradle as the package ecosystem
    directory: "/" # Root directory of your project, contains `settings.gradle`
    schedule:
      interval: "weekly" # Run updates weekly
  - package-ecosystem: "gradle" # Gradle ecosystem for version catalogs
    directory: "/gradle" # Location of `libs.versions.toml`
    schedule:
      interval: "weekly" # Run updates weekly
  - package-ecosystem: "github-actions" # Optional: Update GitHub Actions workflows
    directory: "/" # Location of GitHub Actions workflows (if any in `.github/workflows`)
    schedule:
      interval: "weekly"