[libraries]
ratis-server = { module = "org.apache.ratis:ratis-server", version.ref = "ratis" }
ratis-grpc = { module = "org.apache.ratis:ratis-grpc", version.ref = "ratis" }

[versions]
ratis = "3.1.3"